CREATE TABLE [dw].[dim_product_temp] (
    [ProductID]              INT            NOT NULL,
    [ProductName]            NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ProductAlternateKey]    NVARCHAR (25)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [StandardCost]           MONEY          NOT NULL,
    [FinishedGoodsFlag]      BIT            NOT NULL,
    [Color]                  NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ListPrice]              MONEY          NOT NULL,
    [Size]                   NVARCHAR (5)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SizeUnitMeasureCode]    NCHAR (3)      COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Weight]                 DECIMAL (8, 2) NOT NULL,
    [WeightUnitMeasureCode]  NCHAR (3)      COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DaysToManufacture]      INT            NOT NULL,
    [ProductLine]            NCHAR (3)      COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Class]                  NCHAR (3)      COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Style]                  NCHAR (3)      COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ProductCategoryID]      INT            NOT NULL,
    [ProductCategoryName]    NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ProductSubcategoryID]   INT            NOT NULL,
    [ProductSubcategoryName] NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ProductModelID]         INT            NOT NULL,
    [ProductModelName]       NVARCHAR (50)  NOT NULL,
    [SellStartDate]          DATETIME       NOT NULL,
    [SellEndDate]            DATETIME       NOT NULL,
    [SourceModifiedDate]     DATETIME       NOT NULL,
    [ManufactoryID]          NVARCHAR (255) NOT NULL,
    [ManufactoryName]        NVARCHAR (255) NOT NULL,
    [DateFrom]               NVARCHAR (255) NOT NULL,
    [Dateto]                 NVARCHAR (255) NOT NULL,
    [CurrentFlag]            VARCHAR (7)    NOT NULL,
    [HashCode]               VARBINARY (30) NULL
);

