CREATE TABLE [dw].[dim_product] (
    [ProductKey]             INT            IDENTITY (1, 1) NOT NULL,
    [ProductID]              INT            NULL,
    [ProductName]            NVARCHAR (50)  NULL,
    [ProductAlternateKey]    NVARCHAR (25)  NULL,
    [StandardCost]           MONEY          NULL,
    [FinishedGoodsFlag]      BIT            NULL,
    [Color]                  NVARCHAR (15)  NULL,
    [ListPrice]              MONEY          NULL,
    [Size]                   NVARCHAR (5)   NULL,
    [SizeUnitMeasureCode]    NVARCHAR (3)   NULL,
    [Weight]                 NUMERIC (8, 2) NULL,
    [WeightUnitMeasureCode]  NVARCHAR (3)   NULL,
    [DaysToManufacture]      INT            NULL,
    [ProductLine]            NCHAR (3)      NULL,
    [Class]                  NCHAR (3)      NULL,
    [Style]                  NCHAR (3)      NULL,
    [ProductCategoryID]      INT            NULL,
    [ProductCategoryName]    NVARCHAR (50)  NULL,
    [ProductSubcategoryID]   INT            NULL,
    [ProductSubcategoryName] NVARCHAR (50)  NULL,
    [ProductModelID]         INT            NULL,
    [ProductModelName]       NVARCHAR (50)  NULL,
    [SellStartDate]          DATETIME       NULL,
    [SellEndDate]            DATETIME       NULL,
    [SourceModifiedDate]     DATETIME       NULL,
    [CreatedDate]            DATETIME       DEFAULT (getdate()) NULL,
    [ModifiedDate]           DATETIME       DEFAULT (getdate()) NULL,
    [ManufactoryID]          INT            NULL,
    [ManufactoryName]        NVARCHAR (255) NULL,
    [DateFrom]               DATE           NULL,
    [DateTo]                 DATE           NULL,
    [CurrentFlag]            NVARCHAR (20)  NULL,
    [HashCode]               VARBINARY (30) NULL
);



